// angular-frontend/src/app/shared/components/status-badge/status-badge.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FirmwareStatus, TestResult } from '../../../models';

@Component({
  selector: 'app-status-badge',
  standalone: true,
  imports: [CommonModule],
  template: `
    <span [class]="badgeClass">{{ displayText }}</span>
  `
})
export class StatusBadgeComponent {
  @Input() status: FirmwareStatus | TestResult | string = '';

  get displayText(): string {
    return this.status.replace(/_/g, ' ');
  }

  get badgeClass(): string {
    const base = 'badge ';
    switch (this.status) {
      case 'DRAFT':
        return base + 'bg-gray-100 text-gray-700';
      case 'STAGE1_PENDING':
      case 'STAGE2_PENDING':
      case 'STAGE3_PENDING':
        return base + 'bg-yellow-100 text-yellow-800';
      case 'STAGE1_PASSED':
      case 'STAGE2_PASSED':
        return base + 'bg-blue-100 text-blue-800';
      case 'STAGE1_FAILED':
      case 'STAGE2_FAILED':
        return base + 'bg-red-100 text-red-800';
      case 'APPROVED':
      case 'PASS':
        return base + 'bg-green-100 text-green-800';
      case 'REJECTED':
      case 'FAIL':
        return base + 'bg-red-100 text-red-800';
      case 'SKIP':
        return base + 'bg-gray-100 text-gray-600';
      case 'PENDING':
        return base + 'bg-yellow-100 text-yellow-700';
      case 'IN_PROGRESS':
        return base + 'bg-blue-100 text-blue-800';
      case 'COMPLETED':
        return base + 'bg-green-100 text-green-800';
      case 'SIGNED_OFF':
        return base + 'bg-purple-100 text-purple-800';
      default:
        return base + 'bg-gray-100 text-gray-600';
    }
  }
}

// frontend/src/components/StatusBadge.tsx
import clsx from 'clsx';
import { FirmwareStatus, TestResult } from '../types';

const FW_STATUS_CONFIG: Record<FirmwareStatus, { label: string; cls: string }> = {
  draft:           { label: 'Draft',                cls: 'bg-gray-100 text-gray-700' },
  stage1_pending:  { label: 'Stage 1 Pending',      cls: 'bg-yellow-100 text-yellow-700' },
  stage1_passed:   { label: 'Stage 1 Passed',       cls: 'bg-blue-100 text-blue-700' },
  stage1_failed:   { label: 'Stage 1 Failed',       cls: 'bg-red-100 text-red-700' },
  stage2_pending:  { label: 'Stage 2 Pending',      cls: 'bg-yellow-100 text-yellow-700' },
  stage2_passed:   { label: 'Stage 2 Passed',       cls: 'bg-blue-100 text-blue-700' },
  stage2_failed:   { label: 'Stage 2 Failed',       cls: 'bg-red-100 text-red-700' },
  stage3_pending:  { label: 'Stage 3 Pending',      cls: 'bg-purple-100 text-purple-700' },
  approved:        { label: 'Approved',             cls: 'bg-green-100 text-green-700' },
  rejected:        { label: 'Rejected',             cls: 'bg-red-100 text-red-700' },
};

const RESULT_CONFIG: Record<TestResult, { label: string; cls: string }> = {
  pass:    { label: 'PASS',    cls: 'bg-green-100 text-green-700' },
  fail:    { label: 'FAIL',    cls: 'bg-red-100 text-red-700' },
  skip:    { label: 'SKIP',    cls: 'bg-yellow-100 text-yellow-700' },
  pending: { label: 'PENDING', cls: 'bg-gray-100 text-gray-600' },
};

export function FirmwareStatusBadge({ status }: { status: FirmwareStatus }) {
  const cfg = FW_STATUS_CONFIG[status] || { label: status, cls: 'bg-gray-100 text-gray-700' };
  return (
    <span className={clsx('badge', cfg.cls)}>{cfg.label}</span>
  );
}

export function TestResultBadge({ result }: { result: TestResult }) {
  const cfg = RESULT_CONFIG[result];
  return (
    <span className={clsx('badge', cfg.cls)}>{cfg.label}</span>
  );
}
