// frontend/src/components/Layout.tsx
import React, { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import {
  LayoutDashboard, Cpu, FlaskConical, Car, Award,
  ClipboardList, LogOut, Menu, X, ChevronRight
} from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import clsx from 'clsx';

const ROLE_LABELS: Record<string, string> = {
  admin: 'Admin',
  rd_engineer: 'R&D Engineer',
  rd_head: 'R&D Head',
  operations: 'Operations',
  sales: 'Sales',
};

const NAV = [
  { to: '/',          icon: LayoutDashboard, label: 'Dashboard' },
  { to: '/firmware',  icon: Cpu,             label: 'Firmware Versions' },
  { to: '/stage1',    icon: FlaskConical,    label: 'Stage 1 – Sanity Test' },
  { to: '/stage2',    icon: Car,             label: 'Stage 2 – Field Test' },
  { to: '/stage3',    icon: Award,           label: 'Stage 3 – Final Sign-off' },
  { to: '/changelog', icon: ClipboardList,   label: 'Change Log' },
];

export default function Layout({ children }: { children: React.ReactNode }) {
  const { user, logout } = useAuth();
  const location = useLocation();
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);

  function handleLogout() {
    logout();
    navigate('/login');
  }

  return (
    <div className="flex h-screen overflow-hidden">
      {/* Sidebar */}
      <aside className={clsx(
        'fixed inset-y-0 left-0 z-50 w-64 bg-gray-900 text-white flex flex-col transition-transform duration-200',
        'lg:static lg:translate-x-0',
        open ? 'translate-x-0' : '-translate-x-full'
      )}>
        <div className="flex items-center justify-between px-4 py-4 border-b border-gray-700">
          <div>
            <div className="text-sm font-bold tracking-widest text-blue-400 uppercase">abckedn</div>
            <div className="text-xs text-gray-400 mt-0.5">VTD Testing Protocol</div>
          </div>
          <button className="lg:hidden" onClick={() => setOpen(false)}>
            <X className="w-5 h-5" />
          </button>
        </div>

        <nav className="flex-1 py-4 overflow-y-auto">
          {NAV.map(({ to, icon: Icon, label }) => (
            <Link
              key={to}
              to={to}
              onClick={() => setOpen(false)}
              className={clsx(
                'flex items-center gap-3 px-4 py-2.5 text-sm font-medium transition-colors',
                location.pathname === to
                  ? 'bg-blue-600 text-white'
                  : 'text-gray-300 hover:bg-gray-800 hover:text-white'
              )}
            >
              <Icon className="w-4 h-4 flex-shrink-0" />
              {label}
              {location.pathname === to && <ChevronRight className="w-3 h-3 ml-auto" />}
            </Link>
          ))}
        </nav>

        <div className="border-t border-gray-700 p-4">
          <div className="text-sm font-medium text-white">{user?.name}</div>
          <div className="text-xs text-gray-400">{ROLE_LABELS[user?.role || '']}</div>
          <button
            onClick={handleLogout}
            className="mt-3 flex items-center gap-2 text-xs text-gray-400 hover:text-red-400 transition-colors"
          >
            <LogOut className="w-3.5 h-3.5" />
            Sign out
          </button>
        </div>
      </aside>

      {/* Overlay */}
      {open && (
        <div className="fixed inset-0 z-40 bg-black/50 lg:hidden" onClick={() => setOpen(false)} />
      )}

      {/* Main */}
      <div className="flex-1 flex flex-col min-h-0 overflow-hidden">
        <header className="bg-white border-b border-gray-200 px-4 py-3 flex items-center gap-3 lg:hidden">
          <button onClick={() => setOpen(true)}>
            <Menu className="w-5 h-5" />
          </button>
          <span className="font-semibold text-sm">VTD Testing Protocol</span>
        </header>
        <main className="flex-1 overflow-y-auto p-4 lg:p-6">
          {children}
        </main>
      </div>
    </div>
  );
}

// angular-frontend/src/app/shared/components/layout/layout.component.ts
import { Component, inject, signal } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { Router } from '@angular/router';
import { LucideAngularModule, LayoutDashboard, Cpu, FlaskConical, Car, Award, ScrollText, LogOut, Menu, X, ChevronRight } from 'lucide-angular';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, LucideAngularModule],
  template: `
    <div class="flex h-screen bg-gray-50 overflow-hidden">
      <!-- Mobile overlay -->
      @if (sidebarOpen()) {
        <div
          class="fixed inset-0 bg-black bg-opacity-50 z-20 lg:hidden"
          (click)="sidebarOpen.set(false)"
        ></div>
      }

      <!-- Sidebar -->
      <aside
        [class]="'fixed lg:static inset-y-0 left-0 z-30 flex flex-col w-64 bg-gray-900 text-white transition-transform duration-300 ' + (sidebarOpen() ? 'translate-x-0' : '-translate-x-full lg:translate-x-0')"
      >
        <!-- Logo / Brand -->
        <div class="flex items-center px-6 py-5 border-b border-gray-700">
          <div>
            <h1 class="text-xl font-bold text-blue-400 tracking-wide">abckedn</h1>
            <p class="text-xs text-gray-400 mt-0.5">VTD Testing Protocol</p>
          </div>
          <button
            class="ml-auto lg:hidden text-gray-400 hover:text-white"
            (click)="sidebarOpen.set(false)"
          >
            <lucide-icon [img]="XIcon" [size]="20"></lucide-icon>
          </button>
        </div>

        <!-- Navigation -->
        <nav class="flex-1 px-3 py-4 space-y-1 overflow-y-auto">
          <a
            routerLink="/dashboard"
            routerLinkActive="bg-blue-600 text-white"
            [routerLinkActiveOptions]="{exact: true}"
            class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-gray-300 hover:bg-gray-800 hover:text-white transition-colors text-sm font-medium"
            (click)="closeSidebarOnMobile()"
          >
            <lucide-icon [img]="DashboardIcon" [size]="18"></lucide-icon>
            Dashboard
          </a>

          <a
            routerLink="/firmware"
            routerLinkActive="bg-blue-600 text-white"
            class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-gray-300 hover:bg-gray-800 hover:text-white transition-colors text-sm font-medium"
            (click)="closeSidebarOnMobile()"
          >
            <lucide-icon [img]="CpuIcon" [size]="18"></lucide-icon>
            Firmware Versions
          </a>

          <div class="pt-3 pb-1">
            <p class="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider">Testing Stages</p>
          </div>

          <a
            routerLink="/stage/1"
            routerLinkActive="bg-blue-600 text-white"
            class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-gray-300 hover:bg-gray-800 hover:text-white transition-colors text-sm font-medium"
            (click)="closeSidebarOnMobile()"
          >
            <lucide-icon [img]="FlaskIcon" [size]="18"></lucide-icon>
            Stage 1 – Sanity Test
          </a>

          <a
            routerLink="/stage/2"
            routerLinkActive="bg-blue-600 text-white"
            class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-gray-300 hover:bg-gray-800 hover:text-white transition-colors text-sm font-medium"
            (click)="closeSidebarOnMobile()"
          >
            <lucide-icon [img]="CarIcon" [size]="18"></lucide-icon>
            Stage 2 – Field Test
          </a>

          <a
            routerLink="/stage/3"
            routerLinkActive="bg-blue-600 text-white"
            class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-gray-300 hover:bg-gray-800 hover:text-white transition-colors text-sm font-medium"
            (click)="closeSidebarOnMobile()"
          >
            <lucide-icon [img]="AwardIcon" [size]="18"></lucide-icon>
            Stage 3 – Final Sign-off
          </a>

          <div class="pt-3 pb-1">
            <p class="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider">Audit</p>
          </div>

          <a
            routerLink="/changelog"
            routerLinkActive="bg-blue-600 text-white"
            class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-gray-300 hover:bg-gray-800 hover:text-white transition-colors text-sm font-medium"
            (click)="closeSidebarOnMobile()"
          >
            <lucide-icon [img]="ScrollIcon" [size]="18"></lucide-icon>
            Change Log
          </a>
        </nav>

        <!-- User footer -->
        <div class="px-4 py-4 border-t border-gray-700">
          @if (currentUser()) {
            <div class="flex items-center gap-3">
              <div class="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white text-sm font-semibold">
                {{ currentUser()!.name.charAt(0).toUpperCase() }}
              </div>
              <div class="flex-1 min-w-0">
                <p class="text-sm font-medium text-white truncate">{{ currentUser()!.name }}</p>
                <p class="text-xs text-gray-400 truncate">{{ currentUser()!.role }}</p>
              </div>
              <button
                (click)="logout()"
                class="text-gray-400 hover:text-red-400 transition-colors"
                title="Sign out"
              >
                <lucide-icon [img]="LogOutIcon" [size]="18"></lucide-icon>
              </button>
            </div>
          }
        </div>
      </aside>

      <!-- Main content area -->
      <div class="flex-1 flex flex-col min-w-0 overflow-hidden">
        <!-- Mobile header -->
        <header class="lg:hidden flex items-center px-4 py-3 bg-white border-b border-gray-200">
          <button
            (click)="sidebarOpen.set(true)"
            class="text-gray-600 hover:text-gray-900"
          >
            <lucide-icon [img]="MenuIcon" [size]="24"></lucide-icon>
          </button>
          <h1 class="ml-3 text-lg font-bold text-blue-600">abckedn</h1>
        </header>

        <!-- Page content -->
        <main class="flex-1 overflow-y-auto">
          <ng-content></ng-content>
        </main>
      </div>
    </div>
  `
})
export class LayoutComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  sidebarOpen = signal(false);
  currentUser = this.authService.currentUser;

  DashboardIcon = LayoutDashboard;
  CpuIcon = Cpu;
  FlaskIcon = FlaskConical;
  CarIcon = Car;
  AwardIcon = Award;
  ScrollIcon = ScrollText;
  LogOutIcon = LogOut;
  MenuIcon = Menu;
  XIcon = X;
  ChevronIcon = ChevronRight;

  logout(): void {
    this.authService.logout();
    this.router.navigate(['/login']);
  }

  closeSidebarOnMobile(): void {
    if (window.innerWidth < 1024) {
      this.sidebarOpen.set(false);
    }
  }
}
