// frontend/src/pages/Dashboard.tsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Cpu, FlaskConical, Car, Award, CheckCircle, XCircle, Clock, ArrowRight } from 'lucide-react';
import api from '../api/client';
import { Firmware } from '../types';
import { FirmwareStatusBadge } from '../components/StatusBadge';
import { useAuth } from '../contexts/AuthContext';

export default function Dashboard() {
  const [firmware, setFirmware] = useState<Firmware[]>([]);
  const [loading, setLoading] = useState(true);
  const { user } = useAuth();

  useEffect(() => {
    api.get('/firmware').then(r => { setFirmware(r.data); setLoading(false); });
  }, []);

  const stats = {
    total: firmware.length,
    approved: firmware.filter(f => f.status === 'approved').length,
    inProgress: firmware.filter(f => !['draft', 'approved', 'rejected', 'stage1_failed', 'stage2_failed'].includes(f.status)).length,
    failed: firmware.filter(f => ['stage1_failed', 'stage2_failed', 'rejected'].includes(f.status)).length,
  };

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-xl font-bold text-gray-900">Dashboard</h1>
        <p className="text-sm text-gray-500 mt-0.5">Welcome, {user?.name} &mdash; VTD Firmware Testing Protocol (abckedn)</p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        {[
          { icon: Cpu,         label: 'Total Firmware',    value: stats.total,      color: 'text-blue-600',  bg: 'bg-blue-50' },
          { icon: Clock,       label: 'In Progress',       value: stats.inProgress, color: 'text-yellow-600', bg: 'bg-yellow-50' },
          { icon: CheckCircle, label: 'Approved',          value: stats.approved,   color: 'text-green-600', bg: 'bg-green-50' },
          { icon: XCircle,     label: 'Failed/Rejected',   value: stats.failed,     color: 'text-red-600',   bg: 'bg-red-50' },
        ].map(({ icon: Icon, label, value, color, bg }) => (
          <div key={label} className="card p-4">
            <div className={`inline-flex p-2 rounded-lg ${bg} mb-3`}>
              <Icon className={`w-5 h-5 ${color}`} />
            </div>
            <div className="text-2xl font-bold text-gray-900">{value}</div>
            <div className="text-sm text-gray-500">{label}</div>
          </div>
        ))}
      </div>

      {/* Sign-off Pipeline */}
      <div className="card p-5 mb-6">
        <h2 className="text-sm font-semibold text-gray-700 mb-4">Sign-off Pipeline</h2>
        <div className="flex items-center gap-2 flex-wrap">
          {[
            { label: 'Stage 1\nSanity Test', role: 'R&D Head', icon: FlaskConical, color: 'bg-blue-600' },
            { label: 'Stage 2\nField Test',  role: 'Operations',  icon: Car,          color: 'bg-orange-500' },
            { label: 'Stage 3\nFinal',       role: 'Sales Team',  icon: Award,        color: 'bg-purple-600' },
          ].map(({ label, role, icon: Icon, color }, i) => (
            <React.Fragment key={i}>
              <div className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg border border-gray-200 flex-1 min-w-48">
                <div className={`w-9 h-9 ${color} rounded-lg flex items-center justify-center flex-shrink-0`}>
                  <Icon className="w-4 h-4 text-white" />
                </div>
                <div>
                  <div className="text-xs font-semibold text-gray-800 whitespace-pre-line">{label}</div>
                  <div className="text-xs text-gray-500">Sign-off: {role}</div>
                </div>
              </div>
              {i < 2 && <ArrowRight className="w-4 h-4 text-gray-400 flex-shrink-0" />}
            </React.Fragment>
          ))}
        </div>
      </div>

      {/* Recent Firmware */}
      <div className="card">
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100">
          <h2 className="text-sm font-semibold text-gray-700">Recent Firmware Versions</h2>
          <Link to="/firmware" className="text-xs text-blue-600 hover:underline">View all</Link>
        </div>
        {loading ? (
          <div className="p-8 text-center text-sm text-gray-400">Loading…</div>
        ) : firmware.length === 0 ? (
          <div className="p-8 text-center">
            <Cpu className="w-8 h-8 text-gray-300 mx-auto mb-2" />
            <p className="text-sm text-gray-500">No firmware versions yet</p>
            <Link to="/firmware" className="btn-primary mt-3 text-xs">Add Firmware</Link>
          </div>
        ) : (
          <div className="divide-y divide-gray-50">
            {firmware.slice(0, 8).map(fw => (
              <Link
                key={fw.id}
                to={`/firmware/${fw.id}`}
                className="flex items-center justify-between px-5 py-3 hover:bg-gray-50 transition-colors"
              >
                <div>
                  <div className="text-sm font-medium text-gray-900">{fw.version}</div>
                  <div className="text-xs text-gray-500">{fw.device_model} &mdash; {new Date(fw.created_at).toLocaleDateString()}</div>
                </div>
                <FirmwareStatusBadge status={fw.status} />
              </Link>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

// angular-frontend/src/app/pages/dashboard/dashboard.component.ts
import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { FirmwareService } from '../../core/services/firmware.service';
import { StatusBadgeComponent } from '../../shared/components/status-badge/status-badge.component';
import { LayoutComponent } from '../../shared/components/layout/layout.component';
import { Firmware } from '../../models';
import { LucideAngularModule, Cpu, CheckCircle, XCircle, Activity, ArrowRight, ChevronRight } from 'lucide-angular';
import { DatePipe } from '@angular/common';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [RouterLink, StatusBadgeComponent, LayoutComponent, LucideAngularModule, DatePipe],
  template: `
    <app-layout>
      <div class="p-6 max-w-7xl mx-auto">
        <!-- Page header -->
        <div class="mb-6">
          <h1 class="text-2xl font-bold text-gray-900">Dashboard</h1>
          <p class="text-gray-500 text-sm mt-1">Overview of VTD firmware testing pipeline</p>
        </div>

        @if (loading()) {
          <div class="flex items-center justify-center h-64">
            <div class="w-8 h-8 border-4 border-blue-600 border-t-transparent rounded-full animate-spin"></div>
          </div>
        } @else {
          <!-- Stats cards -->
          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
            <div class="card">
              <div class="flex items-center gap-3">
                <div class="w-10 h-10 rounded-lg bg-blue-100 flex items-center justify-center">
                  <lucide-icon [img]="CpuIcon" [size]="20" class="text-blue-600"></lucide-icon>
                </div>
                <div>
                  <p class="text-2xl font-bold text-gray-900">{{ stats().total }}</p>
                  <p class="text-xs text-gray-500">Total Firmware</p>
                </div>
              </div>
            </div>

            <div class="card">
              <div class="flex items-center gap-3">
                <div class="w-10 h-10 rounded-lg bg-yellow-100 flex items-center justify-center">
                  <lucide-icon [img]="ActivityIcon" [size]="20" class="text-yellow-600"></lucide-icon>
                </div>
                <div>
                  <p class="text-2xl font-bold text-gray-900">{{ stats().inProgress }}</p>
                  <p class="text-xs text-gray-500">In Progress</p>
                </div>
              </div>
            </div>

            <div class="card">
              <div class="flex items-center gap-3">
                <div class="w-10 h-10 rounded-lg bg-green-100 flex items-center justify-center">
                  <lucide-icon [img]="CheckIcon" [size]="20" class="text-green-600"></lucide-icon>
                </div>
                <div>
                  <p class="text-2xl font-bold text-gray-900">{{ stats().approved }}</p>
                  <p class="text-xs text-gray-500">Approved</p>
                </div>
              </div>
            </div>

            <div class="card">
              <div class="flex items-center gap-3">
                <div class="w-10 h-10 rounded-lg bg-red-100 flex items-center justify-center">
                  <lucide-icon [img]="XCircleIcon" [size]="20" class="text-red-600"></lucide-icon>
                </div>
                <div>
                  <p class="text-2xl font-bold text-gray-900">{{ stats().failed }}</p>
                  <p class="text-xs text-gray-500">Failed / Rejected</p>
                </div>
              </div>
            </div>
          </div>

          <!-- Sign-off pipeline -->
          <div class="card mb-8">
            <h2 class="text-lg font-semibold text-gray-900 mb-4">Testing Pipeline</h2>
            <div class="flex flex-col sm:flex-row items-center gap-4">
              <!-- Stage 1 -->
              <div class="flex-1 text-center p-4 bg-blue-50 rounded-xl border border-blue-100">
                <div class="w-10 h-10 rounded-full bg-blue-600 text-white flex items-center justify-center mx-auto mb-2 text-sm font-bold">1</div>
                <p class="font-semibold text-gray-800 text-sm">Sanity Test</p>
                <p class="text-xs text-gray-500 mt-1">Initial validation</p>
                <div class="mt-2">
                  <span class="text-lg font-bold text-blue-600">{{ stats().stage1 }}</span>
                  <span class="text-xs text-gray-500 ml-1">active</span>
                </div>
              </div>

              <lucide-icon [img]="ArrowRightIcon" [size]="20" class="text-gray-400 hidden sm:block"></lucide-icon>

              <!-- Stage 2 -->
              <div class="flex-1 text-center p-4 bg-purple-50 rounded-xl border border-purple-100">
                <div class="w-10 h-10 rounded-full bg-purple-600 text-white flex items-center justify-center mx-auto mb-2 text-sm font-bold">2</div>
                <p class="font-semibold text-gray-800 text-sm">Field Test</p>
                <p class="text-xs text-gray-500 mt-1">Real-world testing</p>
                <div class="mt-2">
                  <span class="text-lg font-bold text-purple-600">{{ stats().stage2 }}</span>
                  <span class="text-xs text-gray-500 ml-1">active</span>
                </div>
              </div>

              <lucide-icon [img]="ArrowRightIcon" [size]="20" class="text-gray-400 hidden sm:block"></lucide-icon>

              <!-- Stage 3 -->
              <div class="flex-1 text-center p-4 bg-green-50 rounded-xl border border-green-100">
                <div class="w-10 h-10 rounded-full bg-green-600 text-white flex items-center justify-center mx-auto mb-2 text-sm font-bold">3</div>
                <p class="font-semibold text-gray-800 text-sm">Final Sign-off</p>
                <p class="text-xs text-gray-500 mt-1">Management approval</p>
                <div class="mt-2">
                  <span class="text-lg font-bold text-green-600">{{ stats().stage3 }}</span>
                  <span class="text-xs text-gray-500 ml-1">active</span>
                </div>
              </div>
            </div>
          </div>

          <!-- Recent firmware table -->
          <div class="card">
            <div class="flex items-center justify-between mb-4">
              <h2 class="text-lg font-semibold text-gray-900">Recent Firmware</h2>
              <a routerLink="/firmware" class="text-sm text-blue-600 hover:text-blue-700 flex items-center gap-1">
                View all
                <lucide-icon [img]="ChevronRightIcon" [size]="16"></lucide-icon>
              </a>
            </div>

            @if (recentFirmware().length === 0) {
              <div class="text-center py-8 text-gray-400">
                <lucide-icon [img]="CpuIcon" [size]="40" class="mx-auto mb-2 opacity-30"></lucide-icon>
                <p class="text-sm">No firmware versions found</p>
              </div>
            } @else {
              <div class="overflow-x-auto">
                <table class="w-full text-sm">
                  <thead>
                    <tr class="border-b border-gray-100">
                      <th class="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Version</th>
                      <th class="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Device Model</th>
                      <th class="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Platform</th>
                      <th class="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Status</th>
                      <th class="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Created By</th>
                      <th class="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Date</th>
                      <th class="py-2 px-3"></th>
                    </tr>
                  </thead>
                  <tbody class="divide-y divide-gray-50">
                    @for (fw of recentFirmware(); track fw.id) {
                      <tr class="hover:bg-gray-50 transition-colors">
                        <td class="py-3 px-3 font-mono font-medium text-gray-900">{{ fw.version }}</td>
                        <td class="py-3 px-3 text-gray-600">{{ fw.deviceModel }}</td>
                        <td class="py-3 px-3 text-gray-600">{{ fw.platform }}</td>
                        <td class="py-3 px-3">
                          <app-status-badge [status]="fw.status"></app-status-badge>
                        </td>
                        <td class="py-3 px-3 text-gray-600">{{ fw.createdByName }}</td>
                        <td class="py-3 px-3 text-gray-500 text-xs">{{ fw.createdAt | date:'MMM d, y' }}</td>
                        <td class="py-3 px-3">
                          <a [routerLink]="['/firmware', fw.id]" class="text-blue-600 hover:text-blue-700">
                            <lucide-icon [img]="ChevronRightIcon" [size]="16"></lucide-icon>
                          </a>
                        </td>
                      </tr>
                    }
                  </tbody>
                </table>
              </div>
            }
          </div>
        }
      </div>
    </app-layout>
  `
})
export class DashboardComponent implements OnInit {
  private firmwareService = inject(FirmwareService);

  CpuIcon = Cpu;
  CheckIcon = CheckCircle;
  XCircleIcon = XCircle;
  ActivityIcon = Activity;
  ArrowRightIcon = ArrowRight;
  ChevronRightIcon = ChevronRight;

  allFirmware = signal<Firmware[]>([]);
  loading = signal(true);

  recentFirmware = computed(() => this.allFirmware().slice(0, 8));

  stats = computed(() => {
    const fw = this.allFirmware();
    const inProgressStatuses = ['STAGE1_PENDING', 'STAGE1_PASSED', 'STAGE2_PENDING', 'STAGE2_PASSED', 'STAGE3_PENDING'];
    return {
      total: fw.length,
      inProgress: fw.filter(f => inProgressStatuses.includes(f.status)).length,
      approved: fw.filter(f => f.status === 'APPROVED').length,
      failed: fw.filter(f => ['STAGE1_FAILED', 'STAGE2_FAILED', 'REJECTED'].includes(f.status)).length,
      stage1: fw.filter(f => f.status === 'STAGE1_PENDING').length,
      stage2: fw.filter(f => f.status === 'STAGE2_PENDING').length,
      stage3: fw.filter(f => f.status === 'STAGE3_PENDING').length,
    };
  });

  ngOnInit(): void {
    this.firmwareService.getAll().subscribe({
      next: data => {
        this.allFirmware.set(data);
        this.loading.set(false);
      },
      error: () => {
        this.loading.set(false);
      }
    });
  }
}
